### ISSUE TITLE
Deoplete explodes with “Key not present in Dictionary: complete_position” in a project opening JaneStreet Core?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [copy/deoplete-ocaml#2]
So, if I open a file with these contents,

```ocaml
open Core

let () =
   print_string "Hello, world!"
```

… position my cursor on the last line, number `4`, and then press `o` to start a new line, I immediately get all of these deoplete messages:

(Yes, each message is echoed twice — I have no idea why?)

```
[deoplete] Traceback (most recent call last):
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/ec/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/omni.py", line 73, in _get_complete_position
[deoplete]   File "/Users/ec/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/omni.py", line 73, in _get_complete_position
[deoplete]     complete_pos = self.vim.call(self.__omnifunc, 1, '')
[deoplete]     complete_pos = self.vim.call(self.__omnifunc, 1, '')
[deoplete]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 229, in call
[deoplete]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 229, in call
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 130, in request
[deoplete]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 130, in request
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 97, in request
[deoplete]   File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 97, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):E716: Key not present in Dictionary: complete_position'
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):E716: Key not present in Dictionary: complete_position'
[deoplete] Error occurred calling omnifunction: deoplete#mapping#_completefunc.  Use :messages for error details.
[deoplete] Error occurred calling omnifunction: deoplete#mapping#_completefunc.  Use :messages for error details.
```

The relevant part seems to be the `neovim.api.nvim.NvimError: b'Vim(return):E716: Key not present in Dictionary: complete_position'`; although I can't, for the life of me, figure out where that error is *actually occurring*.

The error doesn't occur when using Merlin's `merlin#Complete` as `omnifunc`, with Deoplete and `deoplete-ocaml` disabled (i.e. hit `o` as described above, then hit `<C-x><C-o>`.) Meanwhile, with Deoplete and `deoplete-ocaml` *enabled*, it works fine if I remove the `open Core` line. As far as I can tell, it's *only* the combination of `deoplete-ocaml`, a new blank line, and `open Core`, that produces the error.

**Comment by ELLIOTTCABLE** [comment]
Ah, so it seems like if you use this, Merlin's own suggested Deoplete configuration conflicts.

I had this in my `.vimrc` from Merlin,

```viml
let g:deoplete#complete_method = "omnifunc"
" ...
let g:deoplete#omni#input_patterns.ocaml = '[^. *\t]\.\w*|\s\w*|#'
```

I found that removing either `g:deoplete#complete_method`, or the `ocaml` key in `g:deoplete#omni#input_patterns`, solves this. Might be worth documenting in the README! `<3`

**Comment by copy** [comment]
I couldn't reproduce the error, but still a good idea to mention it. Thanks, and let me know if you run into any other problems!
