### ISSUE TITLE
asynchronous completion not working

### ISSUE THREAD

**Issue by studiome** [copy/deoplete-ocaml#3]
Thank you for making great plugin!
I use vim8 on macos and debian(using windows subsystem linux).
On mac, I can use completion but on debian cannot. 
In line 134 I find "output" is bytes but str. 
I assume that it causes this trouble.
if "output" is decoded utf-8, It works.
Is it apropriate?

**Comment by studiome** [comment]
Sorry!
not line 134 but line **126!**

**Comment by copy** [comment]
Thanks, I merged your change as it is obviously correct (`communicate` returns a bytes object and `json.loads` expects a string object).

Still, it would be interesting to know where this error came from, do you still have the error message?

**Comment by studiome** [comment]
I appreciate your merge.
It works well !
(I tried making DEBUG flag into True. )
