### ISSUE TITLE
Any doc to help me install this plugin?

### ISSUE THREAD

**Issue by impvd** [copy/deoplete-ocaml#5]
At this moment, I put this `deoplete_ocaml.py` file in `~/.cache/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete`

```bash
~/.c/d/r/g/S/d/r/p/deoplete (master|…) $ ls
__init__.py       deoplete.py       deoplete_ocaml.py exceptions.py     filter
```

I was wondering if maybe this is the right way to install, and how may I update this plugin automatically in future?

**Comment by copy** [comment]
I'm not familiar with deoplete's remote plugin loader. Can you try these suggestions? https://github.com/Shougo/deoplete.nvim/issues/547#issuecomment-331609532

**Comment by impvd** [comment]
@copy I don't know how to make `deoplete` and `deoplete_ocaml` work.

For example, I wrote:

```ocaml
open Base

List.
``` 

And there's no function shows after I typed `List.`, with my `init.vim`:

```vim

" ===== deoplete begin =======
" enable deoplete
let g:deoplete#enable_at_startup = 1

" this is the default, make sure it is not set to "omnifunc" somewhere else in your vimrc
let g:deoplete#complete_method = "complete"

" other completion sources suggested to disable
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources.ocaml = ['buffer', 'around', 'member']

" no delay before completion
let g:deoplete#auto_complete_delay = 0
" ===== deoplete end =======


```

**Comment by studiome** [comment]
Hi, pivdets.
What type of environment do you use??
Linux? macOS? Windows?
vim? neovim?
In addition, did you update this plugin?
Latest version would work, I think.

**Comment by impvd** [comment]
@studiome 

Thanks for your reply. 

macOS, neovim

I don't how to install this plugin.

**Comment by studiome** [comment]
Thank you, pivdets. I use same (macOS, neovim). So you could use it properly. Don't worry!
FIrst, do you use dein? This is Shougo's super plugin!
In init.vim, could you write call dein#add('Shougo/deoplete') and call dein#add('copy/deoplete-ocaml').
and call function "call deplete#update".

Please see https://github.com/Shougo/dein.vim.
I appreciate @copy for making this fantastic plugin! too.

**Comment by studiome** [comment]
Oh, sorry !!
s/deplete#update/dein#update
Be careful not to ypo like me (x_x)

**Comment by impvd** [comment]
thanks a lot
