### ISSUE TITLE
deoplete-ocaml doesn't respect deoplete#min_pattern_length

### ISSUE THREAD

**Issue by silenc3r** [copy/deoplete-ocaml#6]
Maybe I'm doing something wrong, but deoplete shows completion suggestions all the time, not after typing 2 characters as it should. That is I get completion suggestions even after pressing spacebar or creating new line.

I'm using Neovim 2.3 dev.

**Comment by studiome** [comment]
Hi, @silenc3r .
I wonder it is affected the usage of ocamlmerlin...
Now investigating.

**Comment by copy** [comment]
We set [`input_pattern`](https://github.com/Shougo/deoplete.nvim/blob/bf373da4aae4c37b5863406bbe1a7a7e3295ace1/doc/deoplete.txt#L793-L802), which causes deoplete to ignore `min_pattern_length`. This is indeed desirable, as `input_pattern` is more flexible than `min_pattern_length`. All other deoplete plugins also set `input_pattern` for this reason.

That said, I have to admit that the current setting of `input_pattern` is suboptimal and could use some tweaking. I have changed it to display completions after one character. Can you check if this works for you?

**Comment by silenc3r** [comment]
Everything works great now. I'm able to use Tab as Tab again (this was my main issue to be honest.) Thanks!

**Comment by studiome** [comment]
Thanks, @copy. It works!!

**Comment by copy** [comment]
Thanks for the feedback.

If someone else has issues with the completion input pattern, feel free to create a new issue.
